export const DEPARTMENTS = [
  "CEO Office",
  "Engineering Development",
  "Human Capital",
  "PVD",
  "Casting Maintenance",
  "Machining Maintenance",
  "Production Casting",
  "Production Machining",
  "Quality",
  "Sales & Marketing",
  "Secondary",
  "Supply Chain",
  "Warehouse",
  "Store",
  "Furnace",
  "Business Development",
  "SHE",
  "Production Engineering",
  "PMO",
  "IMC",
  "Machining",
  "MAS",
  "TCED",
  "Machining Engineering",
  "DORMAN",
  "Die Maintenance",
  "FME",
  "IT"
];